apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath: # Use hostPath for local testing; for production, use a proper storage class
    path: /mnt/data/grafana